[book]
authors = ["Ariel AxionL"]
description = "一本介绍 Wayland 协议的书"
language = "zh-cmn-Hans-CN"
multilingual = false
src = "src"
title = "The Wayland Protocol（自译中文版）"

[build]
build-dir = "docs"
create-missing = false

[output.html]
default-theme = "light"
mathjax-support = true
git-repository-url = "https://github.com/axionl/the_wayland_protocol_zh_CN"
cname = "wayland.axionl.me"
site-url = "/the_wayland_protocol_zh_CN/"

[output.html.search]
limit-results = 15

[output.html.playground]
editable = false

[output.epub]
